//
// CorrelationsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class CorrelationsAPI: APIBase {
    /**
     Get aggregated correlations
     
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter effect: (query) Variable name of the effect variable for which the user desires correlations (optional)
     - parameter cause: (query) Variable name of the cause variable for which the user desires correlations (optional)
     - parameter correlationCoefficient: (query) Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action (optional)
     - parameter onsetDelay: (query) The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. (optional)
     - parameter durationOfAction: (query) The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. (optional)
     - parameter updatedAt: (query) The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request. (optional)
     - parameter limit: (query) The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
     - parameter offset: (query) Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
     - parameter sort: (query) Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
     - parameter outcomesOfInterest: (query) Only include correlations for which the effect is an outcome of interest for the user (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1AggregatedCorrelationsGet(accessToken accessToken: String? = nil, userId: Int32? = nil, effect: String? = nil, cause: String? = nil, correlationCoefficient: String? = nil, onsetDelay: String? = nil, durationOfAction: String? = nil, updatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, sort: Int32? = nil, outcomesOfInterest: Bool? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1AggregatedCorrelationsGetWithRequestBuilder(accessToken: accessToken, userId: userId, effect: effect, cause: cause, correlationCoefficient: correlationCoefficient, onsetDelay: onsetDelay, durationOfAction: durationOfAction, updatedAt: updatedAt, limit: limit, offset: offset, sort: sort, outcomesOfInterest: outcomesOfInterest).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get aggregated correlations
     - GET /v1/aggregatedCorrelations
     - Get correlations based on the anonymized aggregate data from all QuantiModo users.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter effect: (query) Variable name of the effect variable for which the user desires correlations (optional)
     - parameter cause: (query) Variable name of the cause variable for which the user desires correlations (optional)
     - parameter correlationCoefficient: (query) Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action (optional)
     - parameter onsetDelay: (query) The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. (optional)
     - parameter durationOfAction: (query) The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. (optional)
     - parameter updatedAt: (query) The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request. (optional)
     - parameter limit: (query) The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
     - parameter offset: (query) Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
     - parameter sort: (query) Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
     - parameter outcomesOfInterest: (query) Only include correlations for which the effect is an outcome of interest for the user (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1AggregatedCorrelationsGetWithRequestBuilder(accessToken accessToken: String? = nil, userId: Int32? = nil, effect: String? = nil, cause: String? = nil, correlationCoefficient: String? = nil, onsetDelay: String? = nil, durationOfAction: String? = nil, updatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, sort: Int32? = nil, outcomesOfInterest: Bool? = nil) -> RequestBuilder<[Correlation]> {
        let path = "/v1/aggregatedCorrelations"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "effect": effect,
            "cause": cause,
            "correlationCoefficient": correlationCoefficient,
            "onsetDelay": onsetDelay,
            "durationOfAction": durationOfAction,
            "updatedAt": updatedAt,
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "outcomesOfInterest": outcomesOfInterest
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Store or Update a Correlation
     
     - parameter body: (body) Provides correlation data 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1AggregatedCorrelationsPost(body body: PostCorrelation, accessToken: String? = nil, userId: Int32? = nil, completion: ((error: ErrorType?) -> Void)) {
        v1AggregatedCorrelationsPostWithRequestBuilder(body: body, accessToken: accessToken, userId: userId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Store or Update a Correlation
     - POST /v1/aggregatedCorrelations
     - Add correlation
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     
     - parameter body: (body) Provides correlation data 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func v1AggregatedCorrelationsPostWithRequestBuilder(body body: PostCorrelation, accessToken: String? = nil, userId: Int32? = nil) -> RequestBuilder<Void> {
        let path = "/v1/aggregatedCorrelations"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get correlations
     
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter effect: (query) Variable name of the effect variable for which the user desires correlations (optional)
     - parameter cause: (query) Variable name of the cause variable for which the user desires correlations (optional)
     - parameter correlationCoefficient: (query) Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action (optional)
     - parameter onsetDelay: (query) The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. (optional)
     - parameter durationOfAction: (query) The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. (optional)
     - parameter updatedAt: (query) The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request. (optional)
     - parameter limit: (query) The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
     - parameter offset: (query) Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
     - parameter sort: (query) Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
     - parameter outcomesOfInterest: (query) Only include correlations for which the effect is an outcome of interest for the user (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1CorrelationsGet(accessToken accessToken: String? = nil, userId: Int32? = nil, effect: String? = nil, cause: String? = nil, correlationCoefficient: String? = nil, onsetDelay: String? = nil, durationOfAction: String? = nil, updatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, sort: Int32? = nil, outcomesOfInterest: Bool? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1CorrelationsGetWithRequestBuilder(accessToken: accessToken, userId: userId, effect: effect, cause: cause, correlationCoefficient: correlationCoefficient, onsetDelay: onsetDelay, durationOfAction: durationOfAction, updatedAt: updatedAt, limit: limit, offset: offset, sort: sort, outcomesOfInterest: outcomesOfInterest).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get correlations
     - GET /v1/correlations
     - Get correlations based on data from a single user.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter effect: (query) Variable name of the effect variable for which the user desires correlations (optional)
     - parameter cause: (query) Variable name of the cause variable for which the user desires correlations (optional)
     - parameter correlationCoefficient: (query) Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action (optional)
     - parameter onsetDelay: (query) The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. (optional)
     - parameter durationOfAction: (query) The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. (optional)
     - parameter updatedAt: (query) The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request. (optional)
     - parameter limit: (query) The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
     - parameter offset: (query) Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
     - parameter sort: (query) Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
     - parameter outcomesOfInterest: (query) Only include correlations for which the effect is an outcome of interest for the user (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1CorrelationsGetWithRequestBuilder(accessToken accessToken: String? = nil, userId: Int32? = nil, effect: String? = nil, cause: String? = nil, correlationCoefficient: String? = nil, onsetDelay: String? = nil, durationOfAction: String? = nil, updatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, sort: Int32? = nil, outcomesOfInterest: Bool? = nil) -> RequestBuilder<[Correlation]> {
        let path = "/v1/correlations"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "effect": effect,
            "cause": cause,
            "correlationCoefficient": correlationCoefficient,
            "onsetDelay": onsetDelay,
            "durationOfAction": durationOfAction,
            "updatedAt": updatedAt,
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "outcomesOfInterest": outcomesOfInterest
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Search user correlations for a given cause
     
     - parameter organizationId: (path) Organization ID 
     - parameter userId2: (path) User id 
     - parameter variableName: (path) Effect variable name 
     - parameter organizationToken: (query) Organization access token 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter includePublic: (query) Include public correlations, Can be \&quot;1\&quot; or empty. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGet(organizationId organizationId: Int32, userId2: Int32, variableName: String, organizationToken: String, accessToken: String? = nil, userId: Int32? = nil, includePublic: String? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGetWithRequestBuilder(organizationId: organizationId, userId2: userId2, variableName: variableName, organizationToken: organizationToken, accessToken: accessToken, userId: userId, includePublic: includePublic).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search user correlations for a given cause
     - GET /v1/organizations/{organizationId}/users/{userId}/variables/{variableName}/causes
     - Returns average of all correlations and votes for all user cause variables for a given cause. If parameter \"include_public\" is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter organizationId: (path) Organization ID 
     - parameter userId2: (path) User id 
     - parameter variableName: (path) Effect variable name 
     - parameter organizationToken: (query) Organization access token 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter includePublic: (query) Include public correlations, Can be \&quot;1\&quot; or empty. (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGetWithRequestBuilder(organizationId organizationId: Int32, userId2: Int32, variableName: String, organizationToken: String, accessToken: String? = nil, userId: Int32? = nil, includePublic: String? = nil) -> RequestBuilder<[Correlation]> {
        var path = "/v1/organizations/{organizationId}/users/{userId}/variables/{variableName}/causes"
        path = path.stringByReplacingOccurrencesOfString("{organizationId}", withString: "\(organizationId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{userId}", withString: "\(userId2)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{variableName}", withString: "\(variableName)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "organization_token": organizationToken,
            "includePublic": includePublic
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Search user correlations for a given cause
     
     - parameter organizationId: (path) Organization ID 
     - parameter userId2: (path) User id 
     - parameter variableName: (path) Cause variable name 
     - parameter organizationToken: (query) Organization access token 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter includePublic: (query) Include public correlations, Can be \&quot;1\&quot; or empty. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGet(organizationId organizationId: Int32, userId2: Int32, variableName: String, organizationToken: String, accessToken: String? = nil, userId: Int32? = nil, includePublic: String? = nil, completion: ((data: [CommonResponse]?, error: ErrorType?) -> Void)) {
        v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGetWithRequestBuilder(organizationId: organizationId, userId2: userId2, variableName: variableName, organizationToken: organizationToken, accessToken: accessToken, userId: userId, includePublic: includePublic).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search user correlations for a given cause
     - GET /v1/organizations/{organizationId}/users/{userId}/variables/{variableName}/effects
     - Returns average of all correlations and votes for all user cause variables for a given effect. If parameter \"include_public\" is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "success" : true,
  "message" : "aeiou",
  "status" : ""
} ]}]
     
     - parameter organizationId: (path) Organization ID 
     - parameter userId2: (path) User id 
     - parameter variableName: (path) Cause variable name 
     - parameter organizationToken: (query) Organization access token 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter includePublic: (query) Include public correlations, Can be \&quot;1\&quot; or empty. (optional)

     - returns: RequestBuilder<[CommonResponse]> 
     */
    public class func v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGetWithRequestBuilder(organizationId organizationId: Int32, userId2: Int32, variableName: String, organizationToken: String, accessToken: String? = nil, userId: Int32? = nil, includePublic: String? = nil) -> RequestBuilder<[CommonResponse]> {
        var path = "/v1/organizations/{organizationId}/users/{userId}/variables/{variableName}/effects"
        path = path.stringByReplacingOccurrencesOfString("{organizationId}", withString: "\(organizationId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{userId}", withString: "\(userId2)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{variableName}", withString: "\(variableName)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "organization_token": organizationToken,
            "include_public": includePublic
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[CommonResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get average correlations for variables containing search term
     
     - parameter search: (path) Name of the variable that you want to know the causes or effects of. 
     - parameter effectOrCause: (query) Setting this to effect indicates that the searched variable is the effect and that the causes of this variable should be returned. cause indicates that the searched variable is the cause and the effects should be returned. 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter outcomesOfInterest: (query) Only include correlations for which the effect is an outcome of interest for the user (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1PublicCorrelationsSearchSearchGet(search search: String, effectOrCause: String, accessToken: String? = nil, userId: Int32? = nil, outcomesOfInterest: Bool? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1PublicCorrelationsSearchSearchGetWithRequestBuilder(search: search, effectOrCause: effectOrCause, accessToken: accessToken, userId: userId, outcomesOfInterest: outcomesOfInterest).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get average correlations for variables containing search term
     - GET /v1/public/correlations/search/{search}
     - Returns the average correlations from all users for all public variables that contain the characters in the search query. Returns average of all users public variable correlations with a specified cause or effect.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter search: (path) Name of the variable that you want to know the causes or effects of. 
     - parameter effectOrCause: (query) Setting this to effect indicates that the searched variable is the effect and that the causes of this variable should be returned. cause indicates that the searched variable is the cause and the effects should be returned. 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter outcomesOfInterest: (query) Only include correlations for which the effect is an outcome of interest for the user (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1PublicCorrelationsSearchSearchGetWithRequestBuilder(search search: String, effectOrCause: String, accessToken: String? = nil, userId: Int32? = nil, outcomesOfInterest: Bool? = nil) -> RequestBuilder<[Correlation]> {
        var path = "/v1/public/correlations/search/{search}"
        path = path.stringByReplacingOccurrencesOfString("{search}", withString: "\(search)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "effectOrCause": effectOrCause,
            "outcomesOfInterest": outcomesOfInterest
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Search user correlations for a given effect
     
     - parameter variableName: (path) Effect variable name 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1VariablesVariableNameCausesGet(variableName variableName: String, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1VariablesVariableNameCausesGetWithRequestBuilder(variableName: variableName).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search user correlations for a given effect
     - GET /v1/variables/{variableName}/causes
     - Returns average of all correlations and votes for all user cause variables for a given effect
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter variableName: (path) Effect variable name 

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1VariablesVariableNameCausesGetWithRequestBuilder(variableName variableName: String) -> RequestBuilder<[Correlation]> {
        var path = "/v1/variables/{variableName}/causes"
        path = path.stringByReplacingOccurrencesOfString("{variableName}", withString: "\(variableName)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Search user correlations for a given cause
     
     - parameter variableName: (path) Cause variable name 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter correlationCoefficient: (query) You can use this to get effects with correlations greater than or less than 0 (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1VariablesVariableNameEffectsGet(variableName variableName: String, accessToken: String? = nil, userId: Int32? = nil, correlationCoefficient: String? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1VariablesVariableNameEffectsGetWithRequestBuilder(variableName: variableName, accessToken: accessToken, userId: userId, correlationCoefficient: correlationCoefficient).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search user correlations for a given cause
     - GET /v1/variables/{variableName}/effects
     - Returns average of all correlations and votes for all user effect variables for a given cause
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter variableName: (path) Cause variable name 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter correlationCoefficient: (query) You can use this to get effects with correlations greater than or less than 0 (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1VariablesVariableNameEffectsGetWithRequestBuilder(variableName variableName: String, accessToken: String? = nil, userId: Int32? = nil, correlationCoefficient: String? = nil) -> RequestBuilder<[Correlation]> {
        var path = "/v1/variables/{variableName}/effects"
        path = path.stringByReplacingOccurrencesOfString("{variableName}", withString: "\(variableName)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "correlationCoefficient": correlationCoefficient
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Search public correlations for a given effect
     
     - parameter variableName: (path) Effect variable name 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter correlationCoefficient: (query) You can use this to get causes with correlations greater than or less than 0 (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1VariablesVariableNamePublicCausesGet(variableName variableName: String, accessToken: String? = nil, userId: Int32? = nil, correlationCoefficient: String? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1VariablesVariableNamePublicCausesGetWithRequestBuilder(variableName: variableName, accessToken: accessToken, userId: userId, correlationCoefficient: correlationCoefficient).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search public correlations for a given effect
     - GET /v1/variables/{variableName}/public/causes
     - Returns average of all correlations and votes for all public cause variables for a given effect
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter variableName: (path) Effect variable name 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter correlationCoefficient: (query) You can use this to get causes with correlations greater than or less than 0 (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1VariablesVariableNamePublicCausesGetWithRequestBuilder(variableName variableName: String, accessToken: String? = nil, userId: Int32? = nil, correlationCoefficient: String? = nil) -> RequestBuilder<[Correlation]> {
        var path = "/v1/variables/{variableName}/public/causes"
        path = path.stringByReplacingOccurrencesOfString("{variableName}", withString: "\(variableName)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON(),
            "correlationCoefficient": correlationCoefficient
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Search public correlations for a given cause
     
     - parameter variableName: (path) Cause variable name 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1VariablesVariableNamePublicEffectsGet(variableName variableName: String, accessToken: String? = nil, userId: Int32? = nil, completion: ((data: [Correlation]?, error: ErrorType?) -> Void)) {
        v1VariablesVariableNamePublicEffectsGetWithRequestBuilder(variableName: variableName, accessToken: accessToken, userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search public correlations for a given cause
     - GET /v1/variables/{variableName}/public/effects
     - Returns average of all correlations and votes for all public cause variables for a given cause
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "causeVariableIonIcon" : "aeiou",
  "outcomeDataSources" : "aeiou",
  "studyLinkDynamic" : "aeiou",
  "studyAbstract" : "aeiou",
  "effectVariableImageUrl" : "aeiou",
  "studyDesign" : "aeiou",
  "studyLinkTwitter" : "aeiou",
  "effectVariableIonIcon" : "aeiou",
  "studyBackground" : "aeiou",
  "effectVariableCategoryName" : "aeiou",
  "causeVariableName" : "aeiou",
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "strengthLevel" : "aeiou",
  "studyObjective" : "aeiou",
  "dataSources" : "aeiou",
  "updatedAt" : "2000-01-23T04:56:07.000+00:00",
  "studyResults" : "aeiou",
  "correlationCoefficient" : 1.3579000000000001069366817318950779736042022705078125,
  "durationOfAction" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkFacebook" : "aeiou",
  "optimalPearsonProduct" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "dataAnalysis" : "aeiou",
  "studyTitle" : "aeiou",
  "valuePredictingHighOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "qmScore" : 1.3579000000000001069366817318950779736042022705078125,
  "averageEffectFollowingLowCauseExplanation" : "aeiou",
  "effect" : "aeiou",
  "causeVariableId" : "",
  "valuePredictingLowOutcomeExplanation" : "aeiou",
  "onsetDelay" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkGoogle" : "aeiou",
  "averageDailyHighCause" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableImageUrl" : "aeiou",
  "valuePredictingHighOutcomeExplanation" : "aeiou",
  "effectVariableName" : "aeiou",
  "cause" : "aeiou",
  "numberOfPairs" : 1.3579000000000001069366817318950779736042022705078125,
  "userVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causalityFactor" : 1.3579000000000001069366817318950779736042022705078125,
  "studyLinkStatic" : "aeiou",
  "averageEffect" : 1.3579000000000001069366817318950779736042022705078125,
  "predictorExplanation" : "aeiou",
  "statisticalSignificance" : "aeiou",
  "imageUrl" : "aeiou",
  "averageVote" : 1.3579000000000001069366817318950779736042022705078125,
  "causeVariableDefaultUnitId" : "",
  "causeChanges" : "",
  "reverseCorrelation" : 1.3579000000000001069366817318950779736042022705078125,
  "principalInvestigator" : "aeiou",
  "timestamp" : 1.3579000000000001069366817318950779736042022705078125,
  "effectVariableId" : "aeiou",
  "averageEffectFollowingLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "averageDailyLowCause" : 1.3579000000000001069366817318950779736042022705078125,
  "significanceExplanation" : "aeiou",
  "averageEffectFollowingHighCauseExplanation" : "aeiou",
  "causeVariableCategoryName" : "aeiou",
  "causeVariableCombinationOperation" : "aeiou",
  "valuePredictingLowOutcome" : 1.3579000000000001069366817318950779736042022705078125,
  "gaugeImage" : "aeiou",
  "studyLimitations" : "aeiou",
  "effectSize" : "aeiou",
  "causeUnit" : "aeiou"
} ]}]
     
     - parameter variableName: (path) Cause variable name 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)

     - returns: RequestBuilder<[Correlation]> 
     */
    public class func v1VariablesVariableNamePublicEffectsGetWithRequestBuilder(variableName variableName: String, accessToken: String? = nil, userId: Int32? = nil) -> RequestBuilder<[Correlation]> {
        var path = "/v1/variables/{variableName}/public/effects"
        path = path.stringByReplacingOccurrencesOfString("{variableName}", withString: "\(variableName)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "access_token": accessToken,
            "userId": userId?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Correlation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Delete vote
     
     - parameter body: (body) The cause and effect variable names for the predictor vote to be deleted. 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1VotesDeletePost(body body: VoteDelete, accessToken: String? = nil, userId: Int32? = nil, completion: ((data: CommonResponse?, error: ErrorType?) -> Void)) {
        v1VotesDeletePostWithRequestBuilder(body: body, accessToken: accessToken, userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Delete vote
     - POST /v1/votes/delete
     - Delete previously posted vote
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example={
  "success" : true,
  "message" : "aeiou",
  "status" : ""
}}]
     
     - parameter body: (body) The cause and effect variable names for the predictor vote to be deleted. 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)

     - returns: RequestBuilder<CommonResponse> 
     */
    public class func v1VotesDeletePostWithRequestBuilder(body body: VoteDelete, accessToken: String? = nil, userId: Int32? = nil) -> RequestBuilder<CommonResponse> {
        let path = "/v1/votes/delete"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<CommonResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Post or update vote
     
     - parameter body: (body) Contains the cause variable, effect variable, and vote value. 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func v1VotesPost(body body: PostVote, accessToken: String? = nil, userId: Int32? = nil, completion: ((data: CommonResponse?, error: ErrorType?) -> Void)) {
        v1VotesPostWithRequestBuilder(body: body, accessToken: accessToken, userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Post or update vote
     - POST /v1/votes
     - This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example={
  "success" : true,
  "message" : "aeiou",
  "status" : ""
}}]
     
     - parameter body: (body) Contains the cause variable, effect variable, and vote value. 
     - parameter accessToken: (query) User&#39;s OAuth2 access token (optional)
     - parameter userId: (query) User&#39;s id (optional)

     - returns: RequestBuilder<CommonResponse> 
     */
    public class func v1VotesPostWithRequestBuilder(body body: PostVote, accessToken: String? = nil, userId: Int32? = nil) -> RequestBuilder<CommonResponse> {
        let path = "/v1/votes"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<CommonResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
