//
// UnitsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class UnitsAPI: APIBase {
    /**
     Get unit categories
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getUnitCategories(completion: ((data: [UnitCategory]?, error: ErrorType?) -> Void)) {
        getUnitCategoriesWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get unit categories
     - GET /v3/unitCategories
     - Get a list of the categories of measurement units such as 'Distance', 'Duration', 'Energy', 'Frequency', 'Miscellany', 'Pressure', 'Proportion', 'Rating', 'Temperature', 'Volume', and 'Weight'.
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "name" : "name",
  "id" : 4,
  "standardUnitAbbreviatedName" : "standardUnitAbbreviatedName"
}, {
  "name" : "name",
  "id" : 4,
  "standardUnitAbbreviatedName" : "standardUnitAbbreviatedName"
} ]}]

     - returns: RequestBuilder<[UnitCategory]> 
     */
    public class func getUnitCategoriesWithRequestBuilder() -> RequestBuilder<[UnitCategory]> {
        let path = "/v3/unitCategories"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[UnitCategory]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get units
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getUnits(completion: ((data: [Unit]?, error: ErrorType?) -> Void)) {
        getUnitsWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get units
     - GET /v3/units
     - Get a list of the available measurement units
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - OAuth:
       - type: oauth2
       - name: quantimodo_oauth2
     - examples: [{contentType=application/json, example=[ {
  "minimumAllowedValue" : 3.616076749251911,
  "advanced" : 6,
  "manualTracking" : 2,
  "categoryName" : "categoryName",
  "maximumAllowedValue" : 7.061401241503109,
  "minimumValue" : 2,
  "unitCategory" : {
    "name" : "name",
    "id" : 4,
    "standardUnitAbbreviatedName" : "standardUnitAbbreviatedName"
  },
  "name" : "name",
  "id" : 5,
  "category" : "Distance",
  "abbreviatedName" : "abbreviatedName",
  "conversionSteps" : [ {
    "operation" : "ADD",
    "value" : 5.962133916683182
  }, {
    "operation" : "ADD",
    "value" : 5.962133916683182
  } ],
  "maximumValue" : 9,
  "categoryId" : 1
}, {
  "minimumAllowedValue" : 3.616076749251911,
  "advanced" : 6,
  "manualTracking" : 2,
  "categoryName" : "categoryName",
  "maximumAllowedValue" : 7.061401241503109,
  "minimumValue" : 2,
  "unitCategory" : {
    "name" : "name",
    "id" : 4,
    "standardUnitAbbreviatedName" : "standardUnitAbbreviatedName"
  },
  "name" : "name",
  "id" : 5,
  "category" : "Distance",
  "abbreviatedName" : "abbreviatedName",
  "conversionSteps" : [ {
    "operation" : "ADD",
    "value" : 5.962133916683182
  }, {
    "operation" : "ADD",
    "value" : 5.962133916683182
  } ],
  "maximumValue" : 9,
  "categoryId" : 1
} ]}]

     - returns: RequestBuilder<[Unit]> 
     */
    public class func getUnitsWithRequestBuilder() -> RequestBuilder<[Unit]> {
        let path = "/v3/units"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Unit]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
