//
// ConnectorInfoHistoryItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ConnectorInfoHistoryItem: JSONEncodable {

    /** Number of measurements */
    public var number_of_measurements: Int?
    /** True if the update was successfull */
    public var success: Bool?
    /** Error message. */
    public var message: String?
    /** Date and time of the update */
    public var created_at: String?
    

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["number_of_measurements"] = self.number_of_measurements
        nillableDictionary["success"] = self.success
        nillableDictionary["message"] = self.message
        nillableDictionary["created_at"] = self.created_at
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
