//
// Explanation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Explanation: JSONEncodable {
    /** Ex: These factors are most predictive of Overall Mood based on your own data. */
    public var description: String?
    public var image: Image?
    /** Ex: ion-ios-person */
    public var ionIcon: String?
    public var startTracking: ExplanationStartTracking?
    /** Ex: Top Predictors of Overall Mood */
    public var title: String?
    /** Embeddable list of study summaries with explanation at the top */
    public var html: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["description"] = self.description
        nillableDictionary["image"] = self.image?.encodeToJSON()
        nillableDictionary["ionIcon"] = self.ionIcon
        nillableDictionary["startTracking"] = self.startTracking?.encodeToJSON()
        nillableDictionary["title"] = self.title
        nillableDictionary["html"] = self.html
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
