//
// JsonErrorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JsonErrorResponse: JSONEncodable {
    /** Error message */
    public var message: String?
    /** Status: \&quot;ok\&quot; or \&quot;error\&quot; */
    public var status: String?
    /** Can be used as body of help info popup */
    public var description: String?
    /** Can be used as title in help info popup */
    public var summary: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["message"] = self.message
        nillableDictionary["status"] = self.status
        nillableDictionary["description"] = self.description
        nillableDictionary["summary"] = self.summary
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
