//
// MeasurementRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MeasurementRange: JSONEncodable {
    /** The timestamp of the earliest measurement for a user. */
    public var lowerLimit: Int32?
    /** The timestamp of the most recent measurement for a user. */
    public var upperLimit: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["lowerLimit"] = self.lowerLimit?.encodeToJSON()
        nillableDictionary["upperLimit"] = self.upperLimit?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
