//
// PostStudyPublishResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostStudyPublishResponse: JSONEncodable {
    /** Ex: ok */
    public var status: String?
    /** Ex: true */
    public var success: Bool?
    /** Can be used as body of help info popup */
    public var description: String?
    /** Can be used as title in help info popup */
    public var summary: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["status"] = self.status
        nillableDictionary["success"] = self.success
        nillableDictionary["description"] = self.description
        nillableDictionary["summary"] = self.summary
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
