//
// StudyImages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class StudyImages: JSONEncodable {
    /** Ex: https://maxcdn.icons8.com/Color/PNG/96/Household/sleeping_in_bed-96.png */
    public var causeVariableImageUrl: String?
    /** Ex: ion-ios-cloudy-night-outline */
    public var causeVariableIonIcon: String?
    /** Ex: https://maxcdn.icons8.com/Color/PNG/96/Cinema/theatre_mask-96.png */
    public var effectVariableImageUrl: String?
    /** Ex: ion-happy-outline */
    public var effectVariableIonIcon: String?
    /** Ex: https://s3.amazonaws.com/quantimodo-docs/images/gauge-moderately-positive-relationship.png */
    public var gaugeImage: String?
    /** Ex: https://s3.amazonaws.com/quantimodo-docs/images/gauge-moderately-positive-relationship-200-200.png */
    public var gaugeImageSquare: String?
    /** Image with gauge and category images */
    public var gaugeSharingImageUrl: String?
    /** Ex: https://s3-us-west-1.amazonaws.com/qmimages/variable_categories_gauges_logo_background/gauge-moderately-positive-relationship_sleep_emotions_logo_background.png */
    public var imageUrl: String?
    /** Image with robot and category images */
    public var robotSharingImageUrl: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["causeVariableImageUrl"] = self.causeVariableImageUrl
        nillableDictionary["causeVariableIonIcon"] = self.causeVariableIonIcon
        nillableDictionary["effectVariableImageUrl"] = self.effectVariableImageUrl
        nillableDictionary["effectVariableIonIcon"] = self.effectVariableIonIcon
        nillableDictionary["gaugeImage"] = self.gaugeImage
        nillableDictionary["gaugeImageSquare"] = self.gaugeImageSquare
        nillableDictionary["gaugeSharingImageUrl"] = self.gaugeSharingImageUrl
        nillableDictionary["imageUrl"] = self.imageUrl
        nillableDictionary["robotSharingImageUrl"] = self.robotSharingImageUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
