//
// TrackingReminderNotificationPost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TrackingReminderNotificationPost: JSONEncodable {
    public enum Action: String { 
        case Skip = "skip"
        case Snooze = "snooze"
        case Track = "track"
    }
    /** track records a measurement for the notification.  snooze changes the notification to 1 hour from now. skip deletes the notification. */
    public var action: Action?
    /** Id of the TrackingReminderNotification */
    public var id: Double?
    /** Optional value to be recorded instead of the tracking reminder default value */
    public var modifiedValue: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["action"] = self.action?.rawValue
        nillableDictionary["id"] = self.id
        nillableDictionary["modifiedValue"] = self.modifiedValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
