//
// Unit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Unit: JSONEncodable {
    public enum Category: String { 
        case Distance = "Distance"
        case Duration = "Duration"
        case Energy = "Energy"
        case Frequency = "Frequency"
        case Miscellany = "Miscellany"
        case Pressure = "Pressure"
        case Proportion = "Proportion"
        case Rating = "Rating"
        case Temperature = "Temperature"
        case Volume = "Volume"
        case Weight = "Weight"
    }
    /** Unit name */
    public var name: String?
    /** Unit abbreviation */
    public var abbreviatedName: String?
    /** Unit category */
    public var category: Category?
    /** The minimum allowed value for measurements. While you can record a value below this minimum, it will be excluded from the correlation analysis. */
    public var minimumAllowedValue: Double?
    /** The maximum allowed value for measurements. While you can record a value above this maximum, it will be excluded from the correlation analysis. */
    public var maximumAllowedValue: Double?
    /** Conversion steps list */
    public var conversionSteps: [ConversionStep]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["abbreviatedName"] = self.abbreviatedName
        nillableDictionary["category"] = self.category?.rawValue
        nillableDictionary["minimumAllowedValue"] = self.minimumAllowedValue
        nillableDictionary["maximumAllowedValue"] = self.maximumAllowedValue
        nillableDictionary["conversionSteps"] = self.conversionSteps?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
