//
// AggregatedCorrelation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AggregatedCorrelation: JSONEncodable {

    /** id */
    public var id: Int?
    /** Pearson correlation coefficient between cause and effect measurements */
    public var correlation: Float?
    /** variable ID of the cause variable for which the user desires correlations */
    public var cause_id: Int?
    /** variable ID of the effect variable for which the user desires correlations */
    public var effect_id: Int?
    /** User estimated or default time after cause measurement before a perceivable effect is observed */
    public var onset_delay: Int?
    /** Time over which the cause is expected to produce a perceivable effect following the onset delay */
    public var duration_of_action: Int?
    /** Number of points that went into the correlation calculation */
    public var number_of_pairs: Int?
    /** cause value that predicts an above average effect value (in default unit for cause variable) */
    public var value_predicting_high_outcome: Float?
    /** cause value that predicts a below average effect value (in default unit for cause variable) */
    public var value_predicting_low_outcome: Float?
    /** Optimal Pearson Product */
    public var optimal_pearson_product: Float?
    /** Vote */
    public var vote: Float?
    /** Number of Users by which correlation is aggregated */
    public var number_of_users: Int?
    /** Number of Correlations by which correlation is aggregated */
    public var number_of_correlations: Int?
    /** A function of the effect size and sample size */
    public var statistical_significance: Float?
    /** Unit of the predictor variable */
    public var cause_unit: String?
    /** Unit ID of the predictor variable */
    public var cause_unit_id: Int?
    /** Cause changes */
    public var cause_changes: Int?
    /** Effect changes */
    public var effect_changes: Int?
    /** Aggregated QM Score */
    public var aggregate_qm_score: Float?
    /** When the record was first created. Use ISO 8601 datetime format */
    public var created_at: NSDate?
    /** When the record in the database was last updated. Use ISO 8601 datetime format */
    public var updated_at: NSDate?
    /** Status */
    public var status: String?
    /** Error Message */
    public var error_message: String?
    /** Last Successful update time */
    public var last_successful_update_time: NSDate?
    /** Correlation when cause and effect are reversed. For any causal relationship, the forward correlation should exceed the reverse correlation */
    public var reverse_pearson_correlation_coefficient: Float?
    /** Predictive Pearson Correlation Coefficient */
    public var predictive_pearson_correlation_coefficient: Float?
    /** Source of data for this correlation */
    public var data_source: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["correlation"] = self.correlation
        nillableDictionary["cause_id"] = self.cause_id
        nillableDictionary["effect_id"] = self.effect_id
        nillableDictionary["onset_delay"] = self.onset_delay
        nillableDictionary["duration_of_action"] = self.duration_of_action
        nillableDictionary["number_of_pairs"] = self.number_of_pairs
        nillableDictionary["value_predicting_high_outcome"] = self.value_predicting_high_outcome
        nillableDictionary["value_predicting_low_outcome"] = self.value_predicting_low_outcome
        nillableDictionary["optimal_pearson_product"] = self.optimal_pearson_product
        nillableDictionary["vote"] = self.vote
        nillableDictionary["number_of_users"] = self.number_of_users
        nillableDictionary["number_of_correlations"] = self.number_of_correlations
        nillableDictionary["statistical_significance"] = self.statistical_significance
        nillableDictionary["cause_unit"] = self.cause_unit
        nillableDictionary["cause_unit_id"] = self.cause_unit_id
        nillableDictionary["cause_changes"] = self.cause_changes
        nillableDictionary["effect_changes"] = self.effect_changes
        nillableDictionary["aggregate_qm_score"] = self.aggregate_qm_score
        nillableDictionary["created_at"] = self.created_at?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updated_at?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["error_message"] = self.error_message
        nillableDictionary["last_successful_update_time"] = self.last_successful_update_time?.encodeToJSON()
        nillableDictionary["reverse_pearson_correlation_coefficient"] = self.reverse_pearson_correlation_coefficient
        nillableDictionary["predictive_pearson_correlation_coefficient"] = self.predictive_pearson_correlation_coefficient
        nillableDictionary["data_source"] = self.data_source
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
