//
// MeasurementRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class MeasurementRange: JSONEncodable {

    /** The timestamp of the earliest measurement for a user. */
    var lowerLimit: Int!
    /** The timestamp of the most recent measurement for a user. */
    var upperLimit: Int?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["lowerLimit"] = self.lowerLimit
        nillableDictionary["upperLimit"] = self.upperLimit
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
