//
// PostCorrelation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class PostCorrelation: JSONEncodable {

    /** Cause variable name */
    var cause: String!
    /** Effect variable name */
    var effect: String!
    /** Correlation value */
    var correlation: Double!
    /** Vote: 0 or 1 */
    var vote: Int?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cause"] = self.cause
        nillableDictionary["effect"] = self.effect
        nillableDictionary["correlation"] = self.correlation
        nillableDictionary["vote"] = self.vote
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
