//
// UnitConversion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UnitConversion: JSONEncodable {

    /** unit_id */
    public var unit_id: Int?
    /** step in the conversion process */
    public var step_number: Bool?
    /** 0 is add and 1 is multiply */
    public var operation: Bool?
    /** number used in the operation */
    public var value: Float?
    /** When the record was first created. Use ISO 8601 datetime format */
    public var created_at: NSDate?
    /** When the record in the database was last updated. Use ISO 8601 datetime format */
    public var updated_at: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["unit_id"] = self.unit_id
        nillableDictionary["step_number"] = self.step_number
        nillableDictionary["operation"] = self.operation
        nillableDictionary["value"] = self.value
        nillableDictionary["created_at"] = self.created_at?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updated_at?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
