//
// UserTokenSuccessfulResponseInnerUserField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserTokenSuccessfulResponseInnerUserField: JSONEncodable {
    /** WordPress user ID */
    public var id: Int32?
    /** User token */
    public var accessToken: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["access_token"] = self.accessToken
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
