//
// VariableUserSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class VariableUserSettings: JSONEncodable {

    /** User ID */
    var user: Int!
    /** Variable DISPLAY name */
    var variable: String!
    /** Estimated duration of time following the onset delay in which a stimulus produces a perceivable effect */
    var durationOfAction: Int!
    /** fillingValue */
    var fillingValue: Int!
    /** joinWith */
    var joinWith: String!
    /** maximumValue */
    var maximumValue: Float!
    /** minimumValue */
    var minimumValue: Float!
    /** name */
    var name: String!
    /** onsetDelay */
    var onsetDelay: Int!
    /** unit */
    var unit: String!
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["user"] = self.user
        nillableDictionary["variable"] = self.variable
        nillableDictionary["durationOfAction"] = self.durationOfAction
        nillableDictionary["fillingValue"] = self.fillingValue
        nillableDictionary["joinWith"] = self.joinWith
        nillableDictionary["maximumValue"] = self.maximumValue
        nillableDictionary["minimumValue"] = self.minimumValue
        nillableDictionary["name"] = self.name
        nillableDictionary["onsetDelay"] = self.onsetDelay
        nillableDictionary["unit"] = self.unit
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
