//
// VariableNew.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class VariableNew: JSONEncodable {
    public enum CombinationOperation: String { 
        case Mean = "MEAN"
        case Sum = "SUM"
    }
    /** User-defined variable display name. */
    public var name: String?
    /** Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc. */
    public var category: String?
    /** Abbreviated name of the default unit for the variable */
    public var unit: String?
    /** Way to aggregate measurements over time. Options are \&quot;MEAN\&quot; or \&quot;SUM\&quot;.  SUM should be used for things like minutes of exercise.  If you use MEAN for exercise, then a person might exercise more minutes in one day but add separate measurements that were smaller.  So when we are doing correlational analysis, we would think that the person exercised less that day even though they exercised more.  Conversely, we must use MEAN for things such as ratings which cannot be SUMMED. */
    public var combinationOperation: CombinationOperation?
    /** Parent */
    public var parent: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["category"] = self.category
        nillableDictionary["unit"] = self.unit
        nillableDictionary["combinationOperation"] = self.combinationOperation?.rawValue
        nillableDictionary["parent"] = self.parent
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
