//
// Variable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class Variable: JSONEncodable {

    enum CombinationOperation: String { 
        case MEAN = "MEAN"
        case SUM = "SUM"
    }
    
    /** User-defined variable display name. */
    var name: String!
    /** Name used when the variable was originally created in the `variables` table. */
    var originalName: String!
    /** Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc. */
    var category: String!
    /** Abbreviated name of the default unit for the variable */
    var unit: String!
    /** Comma-separated list of source names to limit variables to those sources */
    var sources: String!
    /** Minimum reasonable value for this variable (uses default unit) */
    var minimumValue: Double!
    /** Maximum reasonable value for this variable (uses default unit) */
    var maximumValue: Double!
    /** How to aggregate measurements over time. */
    var combinationOperation: CombinationOperation!
    /** Value for replacing null measurements */
    var fillingValue: Double!
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["originalName"] = self.originalName
        nillableDictionary["category"] = self.category
        nillableDictionary["unit"] = self.unit
        nillableDictionary["sources"] = self.sources
        nillableDictionary["minimumValue"] = self.minimumValue
        nillableDictionary["maximumValue"] = self.maximumValue
        nillableDictionary["combinationOperation"] = self.combinationOperation.rawValue
        nillableDictionary["fillingValue"] = self.fillingValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
