//
// UserTokenRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserTokenRequest: JSONEncodable {

    public var user: UserTokenRequestInnerUserField?
    /** Organization Access token */
    public var organization_access_token: String?
    

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["organization_access_token"] = self.organization_access_token
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
