//
// UnitsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire
import PromiseKit

extension SwaggerClientAPI {
    
    class UnitsAPI: APIBase {
    
        /**
         
         Get unit categories
         
         - GET /unitCategories
         - Get a list of the categories of measurement units such as 'Distance', 'Duration', 'Energy', 'Frequency', 'Miscellany', 'Pressure', 'Proportion', 'Rating', 'Temperature', 'Volume', and 'Weight'.
         - authMethods: [com.wordnik.swagger.codegen.CodegenSecurity@5bba3775]

         :returns: Promise<Response<Void>> 
         */
        func unitCategoriesGet() -> RequestBuilder<Void> {
            let path = "/unitCategories"
            let url = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [:]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder(method: "GET", URLString: url, parameters: parameters, isBody: true)
        }
    
        /**
         
         Get all available units
         
         - GET /units
         - Get all available units
         - authMethods: [com.wordnik.swagger.codegen.CodegenSecurity@505dc36b]
         
         :param: unitName (query) Unit name
         :param: abbreviatedUnitName (query) Restrict the results to a specific unit by providing the unit abbreviation.
         :param: categoryName (query) Restrict the results to a specific unit category by providing the unit category name.

         :returns: Promise<Response<Void>> 
         */
        func unitsGet(#unitName: String?, abbreviatedUnitName: String?, categoryName: String?) -> RequestBuilder<Void> {
            let path = "/units"
            let url = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "unitName": unitName,
                "abbreviatedUnitName": abbreviatedUnitName,
                "categoryName": categoryName
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder(method: "GET", URLString: url, parameters: parameters, isBody: false)
        }
    
    }
}
