//
// VariableAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension SwaggerClientAPI {
    
    public class VariableAPI: APIBase {
    
        /**
         
         Get all Variables
         
         - GET /variables
         - Get all Variables
         - OAuth:
           - type: oauth2
           - name: quantimodo_oauth2
         - examples: [{example={
  "data" : [ {
    "number_of_unique_values" : 1.3579000000000001069366817318950779736042022705078125,
    "default_unit_id" : 123,
    "minimum_allowed_value" : 1.3579000000000001069366817318950779736042022705078125,
    "standard_deviation" : 1.3579000000000001069366817318950779736042022705078125,
    "id" : 123,
    "variable_category_id" : 123,
    "image_url" : "aeiou",
    "maximum_allowed_value" : 1.3579000000000001069366817318950779736042022705078125,
    "most_common_value" : 1.3579000000000001069366817318950779736042022705078125,
    "error_message" : "aeiou",
    "name" : "aeiou",
    "created_at" : "2016-02-09T02:17:55.587+0000",
    "mean" : 1.3579000000000001069366817318950779736042022705078125,
    "client_id" : "aeiou",
    "cause_only" : true,
    "onset_delay" : 123,
    "parent_id" : 123,
    "most_common_unit_id" : 123,
    "number_of_measurements" : 1.3579000000000001069366817318950779736042022705078125,
    "kurtosis" : 1.3579000000000001069366817318950779736042022705078125,
    "status" : "aeiou",
    "number_of_user_variables" : 123,
    "combination_operation" : "aeiou",
    "variance" : 1.3579000000000001069366817318950779736042022705078125,
    "product_url" : "aeiou",
    "outcome" : true,
    "last_successful_update_time" : "2016-02-09T02:17:55.587+0000",
    "median" : 1.3579000000000001069366817318950779736042022705078125,
    "price" : 1.3579000000000001069366817318950779736042022705078125,
    "updated_at" : "2016-02-09T02:17:55.587+0000",
    "filling_value" : 1.3579000000000001069366817318950779736042022705078125,
    "skewness" : 1.3579000000000001069366817318950779736042022705078125,
    "maximum_recorded_value" : 1.3579000000000001069366817318950779736042022705078125,
    "duration_of_action" : 123,
    "public" : 123,
    "minimum_recorded_value" : 1.3579000000000001069366817318950779736042022705078125
  } ],
  "success" : true
}, contentType=application/json}]
         
         - parameter accessToken: (query) User&#39;s OAuth2 access token
         - parameter id: (query) id
         - parameter clientId: (query) The ID of the client application which last created or updated this common variable
         - parameter parentId: (query) ID of the parent variable if this variable has any parent
         - parameter name: (query) User-defined variable display name
         - parameter variableCategoryId: (query) Variable category ID
         - parameter defaultUnitId: (query) ID of the default unit for the variable
         - parameter combinationOperation: (query) How to combine values of this variable (for instance, to see a summary of the values over a month) SUM or MEAN
         - parameter fillingValue: (query) Value for replacing null measurements
         - parameter maximumAllowedValue: (query) Maximum reasonable value for this variable (uses default unit)
         - parameter minimumAllowedValue: (query) Minimum reasonable value for this variable (uses default unit)
         - parameter onsetDelay: (query) Estimated number of seconds that pass before a stimulus produces a perceivable effect
         - parameter durationOfAction: (query) Estimated number of seconds following the onset delay in which a stimulus produces a perceivable effect
         - parameter Swaggerpublic: (query) Is variable public
         - parameter causeOnly: (query) A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user
         - parameter mostCommonValue: (query) Most common value
         - parameter mostCommonUnitId: (query) Most common Unit
         - parameter standardDeviation: (query) Standard Deviation
         - parameter variance: (query) Average variance for this variable based on all user data
         - parameter mean: (query) Mean for this variable based on all user data
         - parameter median: (query) Median for this variable based on all user data
         - parameter numberOfMeasurements: (query) Number of measurements for this variable based on all user data
         - parameter numberOfUniqueValues: (query) Number of unique values for this variable based on all user data
         - parameter skewness: (query) Skewness for this variable based on all user data
         - parameter kurtosis: (query) Kurtosis for this variable based on all user data
         - parameter status: (query) status
         - parameter errorMessage: (query) error_message
         - parameter lastSuccessfulUpdateTime: (query) When this variable or its settings were last updated
         - parameter createdAt: (query) When the record was first created. Use ISO 8601 datetime format
         - parameter updatedAt: (query) When the record was last updated. Use ISO 8601 datetime format
         - parameter productUrl: (query) Product URL
         - parameter imageUrl: (query) Image URL
         - parameter price: (query) Price
         - parameter numberOfUserVariables: (query) Number of users who have data for this variable
         - parameter outcome: (query) Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors.  These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables.
         - parameter minimumRecordedValue: (query) Minimum recorded value of this variable based on all user data
         - parameter maximumRecordedValue: (query) Maximum recorded value of this variable based on all user data
         - parameter limit: (query) The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. The maximum limit is 200 records.
         - parameter offset: (query) OFFSET says to skip that many rows before beginning to return rows to the client. OFFSET 0 is the same as omitting the OFFSET clause. If both OFFSET and LIMIT appear, then OFFSET rows are skipped before starting to count the LIMIT rows that are returned.
         - parameter sort: (query) Sort records by a given field name. If the field name is prefixed with &#39;-&#39;, it will sort in descending order.

         - returns: RequestBuilder<Inline_response_200_34> 
         */
        public class func variablesGet(accessToken accessToken: String?, id: Int?, clientId: String?, parentId: Int?, name: String?, variableCategoryId: Int?, defaultUnitId: Int?, combinationOperation: String?, fillingValue: Double?, maximumAllowedValue: Double?, minimumAllowedValue: Double?, onsetDelay: Int?, durationOfAction: Int?, Swaggerpublic: Int?, causeOnly: Bool?, mostCommonValue: Double?, mostCommonUnitId: Int?, standardDeviation: Double?, variance: Double?, mean: Double?, median: Double?, numberOfMeasurements: Double?, numberOfUniqueValues: Double?, skewness: Double?, kurtosis: Double?, status: String?, errorMessage: String?, lastSuccessfulUpdateTime: String?, createdAt: String?, updatedAt: String?, productUrl: String?, imageUrl: String?, price: Double?, numberOfUserVariables: Int?, outcome: Bool?, minimumRecordedValue: Double?, maximumRecordedValue: Double?, limit: Int?, offset: Int?, sort: String?) -> RequestBuilder<Inline_response_200_34> {
            let path = "/variables"
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "accessToken": accessToken,
                "id": id,
                "clientId": clientId,
                "parentId": parentId,
                "name": name,
                "variableCategoryId": variableCategoryId,
                "defaultUnitId": defaultUnitId,
                "combinationOperation": combinationOperation,
                "fillingValue": fillingValue,
                "maximumAllowedValue": maximumAllowedValue,
                "minimumAllowedValue": minimumAllowedValue,
                "onsetDelay": onsetDelay,
                "durationOfAction": durationOfAction,
                "Swaggerpublic": Swaggerpublic,
                "causeOnly": causeOnly,
                "mostCommonValue": mostCommonValue,
                "mostCommonUnitId": mostCommonUnitId,
                "standardDeviation": standardDeviation,
                "variance": variance,
                "mean": mean,
                "median": median,
                "numberOfMeasurements": numberOfMeasurements,
                "numberOfUniqueValues": numberOfUniqueValues,
                "skewness": skewness,
                "kurtosis": kurtosis,
                "status": status,
                "errorMessage": errorMessage,
                "lastSuccessfulUpdateTime": lastSuccessfulUpdateTime,
                "createdAt": createdAt,
                "updatedAt": updatedAt,
                "productUrl": productUrl,
                "imageUrl": imageUrl,
                "price": price,
                "numberOfUserVariables": numberOfUserVariables,
                "outcome": outcome,
                "minimumRecordedValue": minimumRecordedValue,
                "maximumRecordedValue": maximumRecordedValue,
                "limit": limit,
                "offset": offset,
                "sort": sort
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Inline_response_200_34>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
        }
    
        /**
         
         Store Variable
         
         - POST /variables
         - Allows the client to create a new variable in the `variables` table.
         - OAuth:
           - type: oauth2
           - name: quantimodo_oauth2
         - examples: [{example={
  "data" : {
    "number_of_unique_values" : 1.3579000000000001069366817318950779736042022705078125,
    "default_unit_id" : 123,
    "minimum_allowed_value" : 1.3579000000000001069366817318950779736042022705078125,
    "standard_deviation" : 1.3579000000000001069366817318950779736042022705078125,
    "id" : 123,
    "variable_category_id" : 123,
    "image_url" : "aeiou",
    "maximum_allowed_value" : 1.3579000000000001069366817318950779736042022705078125,
    "most_common_value" : 1.3579000000000001069366817318950779736042022705078125,
    "error_message" : "aeiou",
    "name" : "aeiou",
    "created_at" : "2016-02-09T02:17:55.600+0000",
    "mean" : 1.3579000000000001069366817318950779736042022705078125,
    "client_id" : "aeiou",
    "cause_only" : true,
    "onset_delay" : 123,
    "parent_id" : 123,
    "most_common_unit_id" : 123,
    "number_of_measurements" : 1.3579000000000001069366817318950779736042022705078125,
    "kurtosis" : 1.3579000000000001069366817318950779736042022705078125,
    "status" : "aeiou",
    "number_of_user_variables" : 123,
    "combination_operation" : "aeiou",
    "variance" : 1.3579000000000001069366817318950779736042022705078125,
    "product_url" : "aeiou",
    "outcome" : true,
    "last_successful_update_time" : "2016-02-09T02:17:55.600+0000",
    "median" : 1.3579000000000001069366817318950779736042022705078125,
    "price" : 1.3579000000000001069366817318950779736042022705078125,
    "updated_at" : "2016-02-09T02:17:55.600+0000",
    "filling_value" : 1.3579000000000001069366817318950779736042022705078125,
    "skewness" : 1.3579000000000001069366817318950779736042022705078125,
    "maximum_recorded_value" : 1.3579000000000001069366817318950779736042022705078125,
    "duration_of_action" : 123,
    "public" : 123,
    "minimum_recorded_value" : 1.3579000000000001069366817318950779736042022705078125
  },
  "success" : true
}, contentType=application/json}]
         
         - parameter accessToken: (query) User&#39;s OAuth2 access token
         - parameter body: (body) Variable that should be stored

         - returns: RequestBuilder<Inline_response_200_35> 
         */
        public class func variablesPost(accessToken accessToken: String?, body: Variable?) -> RequestBuilder<Inline_response_200_35> {
            let path = "/variables"
            let URLString = SwaggerClientAPI.basePath + path
            
            let parameters = body?.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<Inline_response_200_35>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
        }
    
        /**
         
         Get Variable
         
         - GET /variables/{id}
         - Get Variable
         - OAuth:
           - type: oauth2
           - name: quantimodo_oauth2
         - examples: [{example={
  "data" : {
    "number_of_unique_values" : 1.3579000000000001069366817318950779736042022705078125,
    "default_unit_id" : 123,
    "minimum_allowed_value" : 1.3579000000000001069366817318950779736042022705078125,
    "standard_deviation" : 1.3579000000000001069366817318950779736042022705078125,
    "id" : 123,
    "variable_category_id" : 123,
    "image_url" : "aeiou",
    "maximum_allowed_value" : 1.3579000000000001069366817318950779736042022705078125,
    "most_common_value" : 1.3579000000000001069366817318950779736042022705078125,
    "error_message" : "aeiou",
    "name" : "aeiou",
    "created_at" : "2016-02-09T02:17:55.603+0000",
    "mean" : 1.3579000000000001069366817318950779736042022705078125,
    "client_id" : "aeiou",
    "cause_only" : true,
    "onset_delay" : 123,
    "parent_id" : 123,
    "most_common_unit_id" : 123,
    "number_of_measurements" : 1.3579000000000001069366817318950779736042022705078125,
    "kurtosis" : 1.3579000000000001069366817318950779736042022705078125,
    "status" : "aeiou",
    "number_of_user_variables" : 123,
    "combination_operation" : "aeiou",
    "variance" : 1.3579000000000001069366817318950779736042022705078125,
    "product_url" : "aeiou",
    "outcome" : true,
    "last_successful_update_time" : "2016-02-09T02:17:55.603+0000",
    "median" : 1.3579000000000001069366817318950779736042022705078125,
    "price" : 1.3579000000000001069366817318950779736042022705078125,
    "updated_at" : "2016-02-09T02:17:55.603+0000",
    "filling_value" : 1.3579000000000001069366817318950779736042022705078125,
    "skewness" : 1.3579000000000001069366817318950779736042022705078125,
    "maximum_recorded_value" : 1.3579000000000001069366817318950779736042022705078125,
    "duration_of_action" : 123,
    "public" : 123,
    "minimum_recorded_value" : 1.3579000000000001069366817318950779736042022705078125
  },
  "success" : true
}, contentType=application/json}]
         
         - parameter id: (path) id of Variable
         - parameter accessToken: (query) User&#39;s OAuth2 access token

         - returns: RequestBuilder<Inline_response_200_35> 
         */
        public class func variablesIdGet(id id: Int, accessToken: String?) -> RequestBuilder<Inline_response_200_35> {
            var path = "/variables/{id}"
            path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "accessToken": accessToken
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Inline_response_200_35>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
        }
    
        /**
         
         Update Variable
         
         - PUT /variables/{id}
         - Update Variable
         - OAuth:
           - type: oauth2
           - name: quantimodo_oauth2
         - examples: [{example={
  "data" : "aeiou",
  "success" : true
}, contentType=application/json}]
         
         - parameter id: (path) id of Variable
         - parameter accessToken: (query) User&#39;s OAuth2 access token
         - parameter body: (body) Variable that should be updated

         - returns: RequestBuilder<Inline_response_200_2> 
         */
        public class func variablesIdPut(id id: Int, accessToken: String?, body: Variable?) -> RequestBuilder<Inline_response_200_2> {
            var path = "/variables/{id}"
            path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let parameters = body?.encodeToJSON() as? [String:AnyObject]

            let requestBuilder: RequestBuilder<Inline_response_200_2>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: false)
        }
    
        /**
         
         Delete Variable
         
         - DELETE /variables/{id}
         - Delete Variable
         - OAuth:
           - type: oauth2
           - name: quantimodo_oauth2
         - examples: [{example={
  "data" : "aeiou",
  "success" : true
}, contentType=application/json}]
         
         - parameter id: (path) id of Variable
         - parameter accessToken: (query) User&#39;s OAuth2 access token

         - returns: RequestBuilder<Inline_response_200_2> 
         */
        public class func variablesIdDelete(id id: Int, accessToken: String?) -> RequestBuilder<Inline_response_200_2> {
            var path = "/variables/{id}"
            path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "accessToken": accessToken
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Inline_response_200_2>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: parameters, isBody: false)
        }
    
    }
}
